language: objective-c

before_install:
    - gem install cocoapods -v 0.33.1 --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty -v 0.1.5 --no-rdoc --no-ri --no-document --quiet
    - cd AeroDoc

script:
    - set -o pipefail && xcodebuild -workspace AeroDoc.xcworkspace -scheme AeroDoc -sdk iphonesimulator -configuration Release clean build | xcpretty -c

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
